### ISSUE TITLE
Text decoding being done too early.

### ISSUE THREAD

**Issue by thynson** [tim-smart/multipasta#23]
https://github.com/tim-smart/multipasta/blob/451de6a06ee4b1d05b5b6903e84ce97b0a277a19/src/internal/headers.ts#L88

Text decoding should only be done when the whole buffer of `key` or `value` was available, so multi-byte character that being splitted into different chunks can be properly decoded.

**Comment by tim-smart** [comment]
Good catch, will take a look at your PR when I have some time.

**Comment by tim-smart** [comment]
Actually this is ok, as header names (not values) can only contain A-Z, a-z, 0–9, hyphen ( - ), or underscore ( _ )

**Comment by thynson** [comment]
Yeah, I didn't read the spec seriously, but for key decoding it has been ensured at the first time that each byte must be a 7bit ASCII at the first time. For only value decoding it should be done in this way.
